[build]
  base = "sdrm-outreach"
  command = "npm run build"
  publish = "build"

[context.production]
  environment = { NODE_ENV = "production" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200